name: ci-checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:

  Checks:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # cache: 'pip'
          

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pylavi
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install pylavi

      - name: Run pylavi Tests
        run: |
          echo running pylavi tests
          # read the LabVIEW version from the .lvversion file
          LV_VERSION=$( <.lvversion )
          # convert to integer
          LV_VERSION=$( printf "%d" LV_VERSION )
          source .venv/bin/activate
          vi_validate \
            --path source \
            --path tests \
            --gt $((LV_VERSION)) --lt $((LV_VERSION+1)) \ 
            --skip *.vit \
            --no-code \
            --breakpoints
          echo finished pylavi tests