name: ci-checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:

  Checks:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # cache: 'pip'
          

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pylavi
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install pylavi

      - name: Run pylavi Tests
        shell: bash
        run: |

          # read the LabVIEW version from the first line of .lvversion file
          LV_VERSION="$(head -n 1 .lvversion)"
          # convert to integer
          LV_VERSION=` echo $LV_VERSION | sed 's/\..*//' `
          source .venv/bin/activate

          # print helpful info
          echo "Verifying:"
          echo "  - Save Version is $LV_VERSION"
          echo "  - Separate Compiled Code"
          echo "  - No Breakpoints"

          # call pylavi
          vi_validate \
            --path source \
            --path tests \
            --gt $LV_VERSION --lt $((LV_VERSION+1)) \
            --skip *.vit \
            --no-code \
            --breakpoints
