name: ci-checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:

  ci-checks:
    uses: vipm-io/OpenG-Tookit/.github/workflows/ci-checks.yml@main
    with:
      labview-version: 20.0
