name: ci-checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:

  Checks:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # cache: 'pip'
          

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pylavi
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install pylavi

      - name: Run pylavi Tests
        shell: bash
        run: |
          echo running pylavi tests
          # read the LabVIEW version from the first line of .lvversion file
          LV_VERSION="$(head -n 1 .lvversion)"
          echo "LV_VERSION: $LV_VERSION"
          # convert to integer
          LV_VERSION=` echo $LV_VERSION | sed 's/\..*//' `
          echo "$LV_VERSION < LV_VERSION < $((LV_VERSION+1))"
          source .venv/bin/activate
          vi_validate --path source --gt 20
          #vi_validate \
          #  --path source \
          #  --path tests \
          #  -g $LV_VERSION -l $((LV_VERSION+1)) \ 
          #  --skip *.vit \
          #  --no-code \
          #  --breakpoints
          echo finished pylavi tests